name: Test RAT System

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  run-tests:
    environment: tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create .env file
        run: |
          echo "MODEL_PROVIDER=openAI" >> .env
          echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" >> .env

      - name: Run tests
        run: pytest tests/ --maxfail=1 --disable-warnings -q
